# Generated by Django 5.1.1 on 2024-10-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_max_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="game_version",
            field=models.CharField(default="000.000.011", max_length=100),
        ),
    ]
